"""Add study tools analysis tables

Revision ID: 12bce08cf866
Revises: 29bf2c878334
Create Date: 2026-02-07 14:42:48.337811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12bce08cf866'
down_revision: Union[str, Sequence[str], None] = '29bf2c878334'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('documents_hash', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('key_points', sa.Text(), nullable=True),
    sa.Column('exam_questions', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_analysis_documents_hash'), 'project_analysis', ['documents_hash'], unique=False)
    op.create_table('project_analysis_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('document_hash', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('key_points', sa.Text(), nullable=True),
    sa.Column('exam_questions', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project_analysis.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_analysis_item_document_hash'), 'project_analysis_item', ['document_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_analysis_item_document_hash'), table_name='project_analysis_item')
    op.drop_table('project_analysis_item')
    op.drop_index(op.f('ix_project_analysis_documents_hash'), table_name='project_analysis')
    op.drop_table('project_analysis')
    # ### end Alembic commands ###
