"""Fix exam_questions type to JSONB

Revision ID: 182cfc8ea7ba
Revises: 51ff46e87034
Create Date: 2026-02-07 21:04:00.248256

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "182cfc8ea7ba"
down_revision: Union[str, Sequence[str], None] = "51ff46e87034"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "project_analysis",
        "exam_questions",
        existing_type=sa.TEXT(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
        postgresql_using="exam_questions::jsonb",
    )
    op.alter_column(
        "project_analysis_item",
        "exam_questions",
        existing_type=sa.TEXT(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
        postgresql_using="exam_questions::jsonb",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "project_analysis_item",
        "exam_questions",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.alter_column(
        "project_analysis",
        "exam_questions",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
