"""Add chat history table

Revision ID: 29bf2c878334
Revises: c40fb840bfdb
Create Date: 2026-02-04 19:58:41.183454

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "29bf2c878334"
down_revision: Union[str, Sequence[str], None] = "c40fb840bfdb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "document",
        sa.Column(
            "processing_status",
            sa.String(length=50),
            nullable=False,
            server_default=sa.text("'pending'"),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("document", "processing_status")
    # ### end Alembic commands ###
