"""Fixed analysis schema

Revision ID: 51ff46e87034
Revises: dd084c819a80
Create Date: 2026-02-07 14:57:11.965382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51ff46e87034'
down_revision: Union[str, Sequence[str], None] = 'dd084c819a80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_analysis_documents_hash'), table_name='project_analysis')
    op.drop_column('project_analysis', 'documents_hash')
    op.add_column('project_analysis_item', sa.Column('documents_hash', sa.String(length=255), nullable=False))
    op.drop_index(op.f('ix_project_analysis_item_document_hash'), table_name='project_analysis_item')
    op.create_index(op.f('ix_project_analysis_item_documents_hash'), 'project_analysis_item', ['documents_hash'], unique=False)
    op.drop_constraint(op.f('project_analysis_item_project_id_fkey'), 'project_analysis_item', type_='foreignkey')
    op.create_foreign_key(None, 'project_analysis_item', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_column('project_analysis_item', 'document_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_analysis_item', sa.Column('document_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'project_analysis_item', type_='foreignkey')
    op.create_foreign_key(op.f('project_analysis_item_project_id_fkey'), 'project_analysis_item', 'project_analysis', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_project_analysis_item_documents_hash'), table_name='project_analysis_item')
    op.create_index(op.f('ix_project_analysis_item_document_hash'), 'project_analysis_item', ['document_hash'], unique=False)
    op.drop_column('project_analysis_item', 'documents_hash')
    op.add_column('project_analysis', sa.Column('documents_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_project_analysis_documents_hash'), 'project_analysis', ['documents_hash'], unique=False)
    # ### end Alembic commands ###
