"""add tsvector for hybrid search

Revision ID: b1defeeb0087
Revises: 182cfc8ea7ba
Create Date: 2026-02-11 17:03:26.489022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b1defeeb0087'
down_revision: Union[str, Sequence[str], None] = '182cfc8ea7ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_chunks', sa.Column('content_tsvector', postgresql.TSVECTOR(), sa.Computed("to_tsvector('simple', chunk_text)", persisted=True), nullable=True))
    op.create_index('ix_document_chunks_content_tsvector', 'document_chunks', ['content_tsvector'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_document_chunks_content_tsvector', table_name='document_chunks', postgresql_using='gin')
    op.drop_column('document_chunks', 'content_tsvector')
    # ### end Alembic commands ###
